openapi: 3.0.3
info:
  title: Postack API
  description: The Postack API provides a Product CRUD Interface
  version: 1.0.0
servers:
  - url: 'http://postack.cloud'
  - url: 'http://localhost'
paths:
  /api/v1/products:
    post:
      tags:
        - Products
      summary: Upload a product
      description: >
        This endpoint is used internally when uploading a product
      operationId: addProduct
      parameters:
       - in: query
         name: page
         schema:
           type: integer
           example: 1
           required: true
           format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Successful operation

      externalDocs:
        description: Learn more about user operations provided by this API.
        url: http://api.example.com/docs/user-operations/
    get:
      tags:
        - Products
      summary: Gets all products
      description: >
        This endpoint allows you to retrieve all products limited to 12 by providing page number as query parameter to cycle through the data
      operationId: getAllProducts
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            example: 1
            required: true
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
      externalDocs:
        description: Learn more about user operations provided by this API.
        url: http://api.example.com/docs/user-operations/
    put:
      tags:
        - Products
      summary: Update product.
      description: >
        A detailed description of the operation.
        Use markdown for rich text representation,
        such as **bold**, *italic*, and [links](https://swagger.io).
      operationId: updateProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
      externalDocs:
        description: Learn more about user operations provided by this API.
        url: http://api.example.com/docs/user-operations/
  /api/v1/products/{id}:
    delete:
      tags:
        - Products
      summary: Delete product by Id
      description: >
        A detailed description of the operation.
        Use markdown for rich text representation,
        such as **bold**, *italic*, and [links](https://swagger.io).
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          description: Product Id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation

      externalDocs:
        description: Learn more about user operations provided by this API.
        url: http://api.example.com/docs/user-operations/
  /api/v1/products/{sub-category}:
    get:
      tags:
        - Products
      summary: Get products by Sub-Category
      description: >
        A detailed description of the operation.
        Use markdown for rich text representation,
        such as **bold**, *italic*, and [links](https://swagger.io).
      operationId: getProductsForSubCategory
      parameters:
        - name: sub-category
          in: path
          description: Sub-category
          required: true
          schema:
            type: string
            enum: [ breakfast, spices, treats, body, wine, whiskey, soft-drinks, detergents, sprays ]
        - in: query
          name: page
          schema:
            type: integer
            example: 1
            required: true
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
      externalDocs:
        description: Learn more about user operations provided by this API.
        url: http://api.example.com/docs/user-operations/
  /api/v1/products/recommended/{category}:
    get:
      tags:
        - Products
      summary: Get recommended products for Category
      description: >
        A detailed description of the operation.
        Use markdown for rich text representation,
        such as **bold**, *italic*, and [links](https://swagger.io).
      operationId: getRecommendedForCategory
      parameters:
        - name: category
          in: path
          description: Category
          required: true
          schema:
            type: string
            enum: [ groceries, body, beverages, cleaning ]
        - in: query
          name: page
          schema:
            type: integer
            example: 1
            required: true
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
      externalDocs:
        description: Learn more about user operations provided by this API.
        url: http://api.example.com/docs/user-operations/
  /api/v1/products/search/{search-term}:
    get:
      tags:
        - Products
      summary: Get products by search
      description: >
        A detailed description of the operation.
        Use markdown for rich text representation,
        such as **bold**, *italic*, and [links](https://swagger.io).
      operationId: getProductsBySearchTerm
      parameters:
        - name: search-term
          in: path
          description: Product Search
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
            example: 1
            required: true
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ProductResponse'
      externalDocs:
        description: Learn more about user operations provided by this API.
        url: http://api.example.com/docs/user-operations/
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
          format: double
        rating:
          type: number
          format: double
        image:
          type: string
        description:
          type: string
        weight:
          type: number
          format: double
        unitMeasure:
          type: string
        quantity:
          type: integer
          format: int64
        category:
          type: string
        subCategory:
          type: string
        supplier:
          type: string
      required:
        - id
        - name
        - price
        - rating
        - image
        - description
        - weight
        - unitMeasure
        - quantity
        - category
        - subCategory
        - supplier
    ProductResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        page:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32


